### ISSUE TITLE
Module error on Subaccount calls

### ISSUE THREAD

**Issue by dchima** [Flutterwave/ravepay-nodejs#35]
## Overivew
I'm getting a few Type_Errors while working with this package. These error occur on both `fetch` and `list` calls for subaccounts.

## Disclamer
I had to download the `master` branch off this repo due to the npm version having an issue with loading its `../services' module.

- *subaccount in dashboard*:
<img width="936" alt="Screenshot 2020-03-18 at 07 35 48" src="https://user-images.githubusercontent.com/37340699/76932393-1c529980-68eb-11ea-9655-a99565f15bba.png">

- *./.env*:
```
FLUTTERWAVE_PUBLIC=[REDACTED]
FLUTTERWAVE_SECRET=[REDACTED]
FLUTTERWAVE_ENCR=[REDACTED]
```
### .fetch()
- *error*:
```
TypeError: _rave.getSecretKey is not a function
    at q.fcall.then._rave (/Users/chima/web/apps/flutter/node_modules/ravepay/services/rave.subaccount.fetch.js:23:37)
    at _fulfilled (/Users/chima/web/apps/flutter/node_modules/q/q.js:854:54)
    at /Users/chima/web/apps/flutter/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/chima/web/apps/flutter/node_modules/q/q.js:816:13)
    at /Users/chima/web/apps/flutter/node_modules/q/q.js:570:49
    at runSingle (/Users/chima/web/apps/flutter/node_modules/q/q.js:137:13)
    at flush (/Users/chima/web/apps/flutter/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
- *function call*:
```javascript
  /**
   * get a subaccount
   * @param {object} req
   * @param {object} res
   * @returns {JSON } A JSON response with the created order.
   */
  async getSubaccount(req, res) {
    try {
      const subaccount = await fetchSubaccount('RS_5D402CF85680EC016AF6FEEEB807C077');
      successResponse(res, { message: 'subaccount retrieved', subaccount });
    } catch (error) {
      errorResponse(res, {});
    }
  },
```
- *service call*:
```javascript
  async fetchSubaccount(id) {
    try {
      const account = await rave.Subaccount.fetch(id);
      return account;
    } catch (error) {
      console.log(error);
      throw new ApiError(400, error.message);
    }
  },
```
### .list()
- *error*:
```
TypeError: Cannot read property 'MORX_DEFAULT' of undefined
    at q.fcall (/Users/chima/web/apps/flutter/node_modules/ravepay/services/rave.subaccount.list.js:14:45)
    at Promise.apply (/Users/chima/web/apps/flutter/node_modules/q/q.js:1185:26)
    at Promise.promise.promiseDispatch (/Users/chima/web/apps/flutter/node_modules/q/q.js:808:41)
    at /Users/chima/web/apps/flutter/node_modules/q/q.js:1411:14
    at runSingle (/Users/chima/web/apps/flutter/node_modules/q/q.js:137:13)
    at flush (/Users/chima/web/apps/flutter/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

- *function call:*
```javascript
  /**
   * list all subaccounts
   * @param {object} req
   * @param {object} res
   * @returns {JSON } A JSON response with the created order.
   */
  async allSubaccounts(req, res) {
    try {
      const accounts = await listSubaccount();
      successResponse(res, { message: 'all subaccounts retrieved', accounts });
    } catch (error) {
      errorResponse(res, {});
    }
  }
```
- *service call*:
```javascript
  /**
   * get all subaccounts
   * @returns {JSON} - Returns json with paystack url
   * @memberof Flutterwave
   */
  async listSubaccount() {
    try {
      const accounts = await rave.Subaccount.list();
      return accounts;
    } catch (error) {
      console.log(error);
      throw new ApiError(400, error.message);
    }
  }
```

**Comment by dchima** [comment]
You can fork/clone my repo [here](https://github.com/pseudogarden/flutter) if you would like to replicate the errors.

**Comment by Angello-droid** [comment]
Hello @dchima 
I just made use of the Node SDK and both subaccount features(List,Fetch) seem to work fine.
It's been almost a year you made this comment , many updates has been to the SDK.
Kindly retry.

**Comment by Angello-droid** [comment]
Hello @dchima
I just made use of the Node SDK and both subaccount features(List, Fetch) seem to work fine.
It's been almost a year you made this comment, many updates have been made to the SDK.
Kindly retry.
